//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CadColaborador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadColaborador()
        {
            this.TBColabProj = new HashSet<ColaboradorProjeto>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Skill do colaborador:")]
        public int IdSkill { get; set; }
        [Display(Name = "Nome:")]
        public string Nome { get; set; }
        [Display(Name = "Tipo de Documento:")]
        public short TipoDocumento { get; set; }
        [Display(Name = "Setor:")]
        public string SetorSquad { get; set; }
        [Display(Name = "Email:")]
        public string Email { get; set; }
    
        public virtual Skill TBSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColaboradorProjeto> TBColabProj { get; set; }
    }
}
