//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CadProjeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CadProjeto()
        {
            this.TBColabProj = new HashSet<ColaboradorProjeto>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Cliente:")]
        public int IdCliente { get; set; }
        [Display(Name = "Nome/Descrição:")]
        public string Descricao { get; set; }
        [Display(Name = "Número de Horas:")]
        public int NumeroHoras { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de Início:")]
        public System.DateTime DataInicio { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Data de Finalização:")]
        public System.DateTime DataTermino { get; set; }

        [Display(Name = "Situação:")]
        public string Situacao { get; set; }
        [Display(Name = "Tipo de Pagamento:")]
        public short TipoPgtoProj { get; set; }
        [Display(Name = "Orçamento:")]
        public double Orcamento { get; set; }
        [Display(Name = "Despesas Adicionais:")]
        public double ValorDespesas { get; set; }
    
        public virtual CadCliente TBCadClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ColaboradorProjeto> TBColabProj { get; set; }
    }
}
