//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Manager.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ColaboradorProjeto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ColaboradorProjeto()
        {
            this.TBHorasTrabalhadas = new HashSet<HoraTrabalhada>();
        }
    
        public int Id { get; set; }

        [DataType(DataType.Currency)]
        [Display(Name = "Valor-hora do Colaborador:")]
        public double ValorHora { get; set; }

        [Display(Name = "Projeto")]
        public int IdProjeto { get; set; }

        [Display(Name = "Colaborador")]
        public int IdColab { get; set; }

        [Display(Name = "Atividade no Projeto:")]
        public string TarefaColab { get; set; }
    
        public virtual CadColaborador TBCadColaboradores { get; set; }
        public virtual CadProjeto TBCadProjeto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoraTrabalhada> TBHorasTrabalhadas { get; set; }
    }
}
